# Generated by Django 4.1.1 on 2022-09-08 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_rename_postcategiry_post_postcategory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='ratingAutor',
            new_name='ratingAuthor',
        ),
    ]
